# Generated by Django 6.0.6 on 2026-06-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('plot', models.TextField()),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
